In [44]:
import torch
import numpy as np
from torch.autograd import Variable

w1=Variable(torch.FloatTensor([[1,2]]),requires_grad=True)
w2=Variable(torch.FloatTensor([3,4]),requires_grad=True)
w3=Variable(torch.FloatTensor([[2],[1]]),requires_grad=True)
res=w1.mm(w3)
   
print(w1)
print(w2)
print(w3)
print(res)
print('grad')

res.backward()
print(w1.grad)
print(w3.grad)


tensor([[ 1.,  2.]])
tensor([ 3.,  4.])
tensor([[ 2.],
        [ 1.]])
tensor([[ 4.]])
grad
tensor([[ 2.,  1.]])
tensor([[ 1.],
        [ 2.]])


In [12]:

import torch
import numpy as np
from torch.autograd import Variable


x=Variable(torch.Tensor([2]),requires_grad=True)
z=Variable(torch.Tensor([3]),requires_grad=True)
y=x**3 + 3*x**2 +3
y.detach_()
res=y*z
print(res)
res.backward(retain_graph=True)
print(x.grad)
print(z.grad)

tar=torch.FloatTensor([20])
res.backward(tar,retain_graph=True)
print(x.grad)
print(z.grad)

tensor([ 69.])
None
tensor([ 23.])
None
tensor([ 483.])
